name: Build Debug APK and Check Mergeability

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KEY1: ${{ secrets.KEY1 }}
      KEY2: ${{ secrets.KEY2 }}
      AI_ENDPOINT: ${{secrets.AI_ENDPOINT}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check if this branch can merge into main
        id: merge_check
        run: |
          git fetch origin main
          git checkout -b test-merge origin/main

          if ! git merge --no-commit --no-ff "$GITHUB_REF_NAME"; then
            echo "conflict=true" >> "$GITHUB_OUTPUT"
            exit 1
          else
            echo "conflict=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Comment on PR if merge conflict exists
        if: steps.merge_check.outputs.conflict == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `❌ This branch cannot be cleanly merged into \`main\`. Please resolve conflicts before merging.`
            })

      - name: Grant Gradle permission
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk